[package]
name = "seatracesrv"
version = "0.1.0"
edition = "2021"
authors = ["Askibin"]

[workspace]
members = [
    "crates/core-model",
    "crates/connectors",
    "crates/aggregator",
    "crates/data-store",
    "crates/delivery",
    "crates/control-api"
, "crates/integration-tests"]

[workspace.dependencies]
tokio = { version = "1.37", features = ["full", "sync", "macros"] }
serde = { version = "1.0", features = ["derive", "alloc"] }
serde_json = "1.0"
async-trait = "0.1"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
h3o = "0.6"
uuid = { version = "1.8", features = ["v4", "serde"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
futures-util = "0.3"
axum = { version = "0.8", features = ["ws"] }
reqwest = { version = "0.12", features = ["json"] }

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
axum.workspace = true

core-model = { path = "crates/core-model" }
connectors = { path = "crates/connectors" }
aggregator = { path = "crates/aggregator" }
data-store = { path = "crates/data-store" }
delivery = { path = "crates/delivery" }
control-api = { path = "crates/control-api" }
