{{- if and (not .Values.secret.existingSecret) .Values.secret.aisStreamApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seatracesrv.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seatracesrv.labels" . | nindent 4 }}
type: Opaque
stringData:
  AISSTREAM_API_KEY: {{ .Values.secret.aisStreamApiKey | quote }}
{{- end }}
