[package]
name = "core-model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
h3o.workspace = true
uuid.workspace = true
async-trait.workspace = true
tokio.workspace = true
progenitor-client = "0.8"
progenitor-impl = "0.8"
typify = "0.5"
reqwest = "0.12"

[build-dependencies]
openapiv3 = "2.0"
progenitor = "0.8"
serde_yaml = "0.9"
